### ISSUE TITLE
Petra should be more resilient against unexpected API input.

### ISSUE THREAD

**Issue by jonathanjuursema** [saproto/petra#2]
Currently, every time the screens API endpoint is unreachable (for example during a software update) Petra crashes. If Petra receives invalid API data back, it should just ignore the data and stick with the last known data. Ideally, it should also notify, for example via Slack or a message on screen, if the API has been unreachable for some time.

**Comment by thijsdortmann** [comment]
This seems to be a combination between Herbert and Petra issues. 1aa7c6909475ca0bb053dc1081a9fe4676b14939 should solve a part of it :)
